### ISSUE TITLE
Migrate Enrolment Pages

### ISSUE THREAD

**Issue by georgetayqy** [ssg-wsg/Sample-Codes#10]
Let's move to migrate the Enrolment pages on Tkinter to Streamlit.

## Tasks

Migration efforts are tracked in PR #13.

- [x] Migrate Create Enrolment Page (**Migrated**)
- [x] Migrate Update Enrolment Page (**Migrated**)
- [x] Migrate Cancel Enrolment Page (**Migrated**)
- [x] Migrate Search Enrolment Page (**Migrated**)
- [x] Migrate View Enrolment Page (**Migrated**)
- [x] Migrate Update Enrolment Page (**Migrated**)

**Comment by georgetayqy** [comment]
Closed as PR #13 is merged.
