### ISSUE TITLE
Migrate Assessment Pages

### ISSUE THREAD

**Issue by georgetayqy** [ssg-wsg/Sample-Codes#12]
Let's move to migrate the Assessment Pages from Tkinter to Streamlit.

## Tasks

Migration efforts are tracked in PR #8.

- [x] Migrate Create Assessment Page (**Migrated**)
- [x] Migrate Update/Void Assessment Page (**Migrated**)
- [x] Migrate Find Assessment Page (**Migrated**)
- [x] Migrate View Assessment Page (**Migrated**)

**Comment by georgetayqy** [comment]
Closed as PR #8 is merged.
