### ISSUE TITLE
Implement SkillsFuture Credit Pay API Pages

### ISSUE THREAD

**Issue by georgetayqy** [ssg-wsg/Sample-Codes#14]
As part of an effort to expand on the set of APIs that Training Providers must implement, let's move to implement the SkillsFuture Credit Pay API into the sample application and create the corresponding Pages that support the operations of the API.

## Tasks

Implementation progress is tracked in PR #9.

- [x] Implement Encryption (SF Credit Claims Request) Page (**Implemented**)
- [x] Implement Decryption (SF Credit Claims Request) Page (**Implemented**)
- [x] Implement Upload Supporting Documents Page (**Implemented**)
- [x] Implement View Claims Page (**Implemented**)
- [x] Implement Cancel Claims Page (**Implemented**)

**Comment by georgetayqy** [comment]
Closed as #9 is merged.
