### ISSUE TITLE
Migrate Course Run Pages

### ISSUE THREAD

**Issue by georgetayqy** [ssg-wsg/Sample-Codes#5]
We need to migrate the 5 main Course Run pages from Tkinter to Streamlit.

This issue will be used to track the overall migration progress.

## Tasks

Progress made towards this issue is done in issue #3.

- [x] Migrate View Course Run: **Migrated**
- [x] Migrate Add Course Run: **Migrated**
- [x] Migrate Delete Course Run: **Migrated**
- [x] Migrate Update Course Run: **Migrated**
- [x] Migrate Course Run Sessions: **Migrated**

**Comment by georgetayqy** [comment]
PR #3 was merged and this is now implemented.
