### ISSUE TITLE
Create CI/CD Pipelines

### ISSUE THREAD

**Issue by georgetayqy** [ssg-wsg/Sample-Codes#6]
# Feature Request

Currently, there are no CI/CD pipelines in place to execute unit/integration/system tests on the demo application.

## Proposed Feature/Solution

Let's move to implement CI/CD pipelines using GitHub Actions, which will handle automated testing of the application, code coverage checks as well as future deployments to cloud platforms if possible.

## Tasks

- [x] Use GitHub Actions to create simple CI/CD pipelines for running unit tests on Python
- [x] Use GitHub Actions to automatically upload code coverage reports to code coverage providers such as *Codecov*
- [x] Use GitHub Actions to automate the deployment of code onto ECS Clusters

**Comment by georgetayqy** [comment]
Pipelines are up and can deploy the application to AWS.
